### ISSUE TITLE
Trigger increment patch by different task

### ISSUE THREAD

**Issue by brainbytes42** [davideas/GrabVer#19]
Thanks for the great tool!

Is there a way to trigger the increment of the patch by a custom task?

e.g. for a plain java application, it would be great if the patch would increment on each 'build' or 'jar'... i tried build.dependsOn(grabverRelease), but that doesn't seem to work at all...
[my usecase: while developing, i just run my application (application::run), but to distribute the software, i use a jar (java::jar).]

I had some hope, when I found the dependsOn parameter in versioning, but that doesn't seem to help, either... wouldn't it possible to have a parameter that i can set to 'jar' for example, and then on each jar building, the patch gets incremented?

support for this usecase would be great - thanks!

**Comment by davideas** [comment]
@brainbytes42, I'm deprecating `dependsOn` in favor of `saveOn` (which gives a better idea of what the plugin does) in **v1.0.1**.

In GrabVer there are 2 checks:
- One at apply time of the script which monitors the runTasks of the gradle command.
- One after evaluation which saves the new versioning.

At the apply time the new versioning is _unknown_, this happens when the `apply` function is performed, for this reason I can't add a property like `incrementOn <taskName>` or `skipOn <taskName>`. (At least I do not know how to do it, for your information, `beforeTask` seems to not work).
Therefore, I invented the task name `grabverRelease` which is written in command line at allows to increment the versioning, and the `dependsOn` (now `saveOn`) that saves to file the new numbers.

To answer at your question, your command should look like `gradle jar grabverRelease` with `dependsOn(saveOn) "jar"`.
However if task `compileJava` is executed, and it should be by default, you don't need to specify dependsOn(saveOn). Read the readme.md.

PS. If somebody knows how to scan the build script when `apply plugin: 'eu.davidea.grabver'` is invoked please let me know.

**Comment by brainbytes42** [comment]
thanks for your explanation!

**Comment by Kiran-B** [comment]
@brainbytes42 Did you get this working? I am trying to use this plugin in a Spring boot app and `version.properties` does not seem to update.

**Comment by brainbytes42** [comment]
No, unfortunately not, but as davideas wrote, it seems not that easy to implement... 😉

**Comment by davideas** [comment]
@Kiran-B, I just tried on a new Spring Boot project: if you sync Gradle with IntelliJ Idea refresh, it gives the impression that it wants save something but if we look at the output log the `runtasks []` is empty so it will not save anything: the behavior is correct.
If you run Gradle with a build task, the `compileJava` is automatically triggered behind and it will save on file the new versioning at the success.

What I can do is to provide a better clearance of what the script is doing and advice on taking an action if no task is specified. However, it is correct to not increase the numbers on syncing due to a manual change of _build.gradle_ file.

But also, by pressing the IntelliJ Run button on toolbar and having the following configuration:
``` gradle
versioning {
    major 1
    minor 0
    preRelease "SNAPSHOT"
}
```
``` batch
20:09:54: Executing task 'explodedWar -x test'...

> Configure project :toolery-ws
====== STARTED GrabVer v1.0.1
INFO - ProjectName 'toolery-ws'
INFO - Versioning module 'toolery-ws'
INFO - Versioning filename 'D:\Pgm\IntelliJIDEAProjects\Toolery\toolery-ws\version.properties'
INFO - Current versioning 1.0.0-SNAPSHOT #1 code=1
INFO - runTasks=[explodedWar]
INFO - Running with normal build => 'Code' version unchanged
INFO - Auto incrementing build number
INFO - Auto resetting patch version
Selected profile is: 'local'
Running script: '../toolery-config/env/local/profile_local.gradle'

> Task :toolery-ws:compileJava
INFO - toolery-ws:compileJava TaskState succeeded
INFO - Saving versioning 1.0.0-SNAPSHOT #2 code=1
====== ENDED GrabVer

> Task :toolery-ws:processResources
> Task :toolery-ws:classes
> Task :toolery-ws:explodedWar

BUILD SUCCESSFUL in 9s
3 actionable tasks: 3 executed
20:10:04: Task execution finished 'explodedWar -x test'.
```

![image](https://user-images.githubusercontent.com/12213847/59296840-2faf4500-8c87-11e9-8b64-573035aa523f.png)

**Comment by Kiran-B** [comment]
I was earlier using Java v11. This was the root cause for generation of empty `version.properties` file. When I switched to Java 1.8 your plugin worked as expected. Another mistake I made was setting `preRelease`. This causes the PATCH to be reset as intended. Please refer to https://github.com/davideas/GrabVer/issues/18#issuecomment-501105999 for detail.

I am able to successfully use this in a Spring Project by using the following:
When I need any command to increment patch I use:
```bash
./gradlew grabverRelease [ACTUAL_TASK]
```

When I need a command to not touch version I use:
```bash
./gradlew grabverSkip [ACTUAL_TASK]
```
