### ISSUE TITLE
empty version.properties

### ISSUE THREAD

**Issue by abouquet** [davideas/GrabVer#21]
Generated version.properties file is empty on first run.

gradlew -version

```
------------------------------------------------------------

Build time:   2019-03-20 11:03:29 UTC
Revision:     f5c64796748a98efdbf6f99f44b6afe08492c2a0

Kotlin:       1.3.21
Groovy:       2.5.4
Ant:          Apache Ant(TM) version 1.9.13 compiled on July 10 2018
JVM:          1.8.0_131 (Oracle Corporation 25.131-b11)
OS:           Windows 10 10.0 amd64
``` 

build output

```
> Configure project :
====== STARTED GrabVer v1.0.1
INFO - ProjectName 'gradle-versioning'
INFO - Versioning root project 'gradle-versioning'
INFO - Versioning filename 'C:\dev\peaks\bees\gradle-versioning\version.properties'
INFO - Current versioning 0.0.0 #0 code=1
INFO - runTasks=[grabverRelease]
INFO - Running with release build => 'Code' version will auto increment
```

**Comment by ilyvion** [comment]
I just tried GrabVer version 0.6.0, 0.7.0, 1.0.0 and 1.0.1, and they either place an empty `version.properties` or just a timestamp in a comment... How is it possible that this bug has been around since forever and never been fixed?

**Comment by davideas** [comment]
Dears, how is your configuration?
``` gradle
versioning {
    // required (number)
    major 1
    minor 0
    // optional, force custom patch (number)
    patch 7
    // optional (any string)
    preRelease "RC1"
    // optional, save new versioning on file on specified <task-name>
    saveOn "<task-name>"
}
```
The new numbers are saved on file if one of these default-task exists: `compileJava`, `assembleDebug`, `assembleRelease`.

Running `gradle grabverRelease` task will trigger only the increase of the _patch_ and _code_ numbers, not the saving, because it does nothing on your project. Please, run it with a real goal as above specified, mainly in a real project or for test purpose you can add `saveOn 'grabverRelease'` in the configuration.
However, I can add `grabverRelease` to the list of tasks to save the file if this is what you suggest.

**Comment by davideas** [comment]
You can check #19 to have further explanation.
