### ISSUE TITLE
Update Java Ordered properties to 1.0.3 or 1.0.4

### ISSUE THREAD

**Issue by Kuglll** [davideas/GrabVer#31]
Currently the latest grabver plugin is using "Java Ordered Properties" version 1.0.2, which is only available at `jcenter`. And since [`jcenter` is shutting down on August 15th](https://jfrog.com/blog/jcenter-sunset/), it might me a good idea to update "Java Ordered Properties" to 1.0.3 or 1.0.4.

**Comment by Kuglll** [comment]
@davideas @mastito03 @jrcacd

**Comment by davideas** [comment]
They continue to change procedures for publishing... it's so annoying. I am already lost.
To prevent any issues, copy the library to a local lib folder and use from there, while I try to figure out the new migration and new setup for new Maven Central.

**Comment by Kuglll** [comment]
Great! Thanks for the response!

**Comment by davideas** [comment]
Well, I have just struggled to clean the project and publish a new version after those years.
It contains repository and dependences upgrade for OrderedProperties 1.0.4 so it doesn't complain anymore.
The plugin was and it is still available in Gradle Plugin Portal. Not using Maven Central yet, because it requires lot more effort for new account migration and signing, etc.
Readme updated.

I will try to have a look at other enhancements in the near future.

**Comment by Kuglll** [comment]
Great! Thanks for the fast answer. I didn't expect that I'll even get one. 😅
